### ISSUE TITLE
On phones with smaller resolutions, the width of the box at the bottom is not consistent

### ISSUE THREAD

**Issue by denzhe22** [AnsonH/plinko-game#14]
![img](https://github.com/AnsonH/plinko-game/assets/4111637/f43892a8-f908-4105-86a4-9a91608097cd)

Hi，
I found that on the phone with a smaller resolution, the width of the box at the bottom was inconsistent, I tried to modify it, and found that it did not work. Is there a proper way to solve this?

**Comment by AnsonH** [comment]
Hi there, this issue does not happen on my newer iOS device (iPhone 13 running iOS 17). 

That's because I'm using [CSS `clamp()`](https://developer.mozilla.org/en-US/docs/Web/CSS/clamp) in the bin row ([code here](https://github.com/AnsonH/plinko-game/blob/v1.0.0/src/lib/components/Plinko/BinsRow.svelte#L50)) to dynamically compute the font size based on viewport width. Seeing the [browser compatibility table](https://developer.mozilla.org/en-US/docs/Web/CSS/clamp#browser_compatibility), are you using Safari version of <13.4?

<img width="500" src="https://github.com/AnsonH/plinko-game/assets/57580593/09ea3936-a13d-4459-99e1-1bbbbed9e015" >

**Comment by AnsonH** [comment]
Won't be fixing this issue since `clamp()` is already have a [support rate of 96.3% globally](https://caniuse.com/?search=clamp()).
